# Generated by Django 3.2 on 2023-09-28 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0035_auto_20230927_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Минимальное время приготовления 1 минута.'), django.core.validators.MaxValueValidator(32000, message='Максимальное время приготовления 32000 минут.')], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество ингредиентов - 1.'), django.core.validators.MaxValueValidator(32000, message='Максимальное количество ингредиентов - 32000.')], verbose_name='Количество'),
        ),
    ]
