# Generated by Django 3.2 on 2023-10-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_alter_recipeingredient_ingredient'),
        ('recipes', '0036_auto_20230928_1751'),
    ]

    operations = [
    ]
